"""Logging module for ItsMeHi.

This module handles the recording of recruiter interactions
by saving questions and answers to a CSV log file.

Functions:
    guardar_logging(pregunta, respuesta): Append a new interaction to the conversation log.
"""

# === Imports ===
import pandas as pd
from pathlib import Path
from datetime import datetime

# === Constants ===
LOGS_DIR = Path("logs")
LOGS_FILE = LOGS_DIR / "itsmehi_chat_logs.csv"

# === Functions ===

def guardar_logging(pregunta: str, respuesta: str) -> None:
    """Append a new recruiter interaction to the conversation log file.

    Args:
        pregunta (str): Question asked by the recruiter.
        respuesta (str): Answer generated by the agent.

    Returns:
        None
    """
    # Ensure logs directory exists
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    
    # Prepare the new log entry
    nueva_entrada = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "pregunta": pregunta,
        "respuesta": respuesta
    }
    
    # If log file exists, append; otherwise, create new DataFrame
    if LOGS_FILE.exists():
        df_logs = pd.read_csv(LOGS_FILE)
        df_logs = pd.concat([df_logs, pd.DataFrame([nueva_entrada])], ignore_index=True)
    else:
        df_logs = pd.DataFrame([nueva_entrada])
    
    # Save updated log
    df_logs.to_csv(LOGS_FILE, index=False)
